### ISSUE TITLE
Deprecating binary-split-streams2

### ISSUE THREAD

**Issue by myndzi** [maxogden/binary-split#11]
I sometimes remember to check up on the package when new node versions come out to make sure its claims are still accurate -- they aren't. I also noticed you switched to through2, which takes care of my original use case for lazy splitting. I'm just writing to mention I deprecated it in favor of this package :)

One thing I did notice is that I may have more thorough tests, so you're welcome to steal them if you like. They seem to pass out of the box with this module.

I was curious but unable to discern why the significant speed difference, maybe it has something to do with optimizations in through2 itself. Anyway, thanks for maintaining this!

**Comment by mourner** [comment]
Sounds great, thanks for letting us know! Would you be up to submitting a PR with more tests from your package?

**Comment by myndzi** [comment]
I could probably do that, dunno why I never seem to have got the alert from your response.

**Comment by myndzi** [comment]
I must have been mistaken, or else this bug where stuff gets joined is the result of a newer version of through2; this package now bombs a number of tests. I've thrown them into this branch: https://github.com/myndzi/binary-split/tree/integrate-new-tests

You can check them with `npm run test2` to see. Since it's a different test runner, and it seems like most of the brokenness is a result of chunks being merged as in the other issue I opened, I'm not going to go through integrating the tests until the base code is working correctly; when you have fixed the base code, I'm happy to do that or work with you on it.
