### ISSUE TITLE
mode that only returns split positions

### ISSUE THREAD

**Issue by maxogden** [maxogden/binary-split#5]
I thought it might be nice to have a flag that made this return the offsets of each newline. the default mode would still remain the same - it would split the buffers for you. but this new mode wouldnt split the buffers, it would just return the position in the byte stream of each newilne that is found

it's an approach similar to what we use in this native module: https://github.com/maxogden/rabin

**Comment by mourner** [comment]
This is nice, but should also be considered for a separate module since just returning offsets is much simpler in implementation (e.g. doesn't require buffer concatenation, etc.).

**Comment by maxogden** [comment]
hmm I sort of agree, but stuff like this would be annoying to maintain in two places https://github.com/maxogden/binary-split/blob/master/index.js#L56-L77

**Comment by soldair** [comment]
Could we replace firstMatch with Buffer.indexOf after merging #6 ?

**Comment by mourner** [comment]
@soldair good catch! Need to do some comparison benchmarks first though.

**Comment by mourner** [comment]
@soldair Buffer.indexOf turned out to be a bit slower, and it's also not 0.12-compatible, so I simplified `firstMatch` function instead.

**Comment by soldair** [comment]
great thanks for letting me know!
