### ISSUE TITLE
mode that includes line ending in line buffer and start position in source stream

### ISSUE THREAD

**Issue by soldair** [maxogden/binary-split#7]
i would love to work on this if these changes are interesting for anyone.

- adding start position as a property of each line buffer makes it really easy to process one line at a time and resume where you left off.
- Including the line ending removes guess work as to the start of the next line

I'm working on a module to use a log file as a changes feed.

**Comment by mourner** [comment]
> Including the line ending removes guess work as to the start of the next line

Can you explain this point more?

**Comment by soldair** [comment]
sure.

instead of "line" i would like to be able to get data events with "line\n"  || line+os.EOL

2 use cases.

one i forgot to mention but is the most important is it removes ambiguity at the end of the stream as to if the final chunk is a complete line or just a partially written fragment.
https://github.com/maxogden/binary-split/blob/master/index.js#L51

including whitespace we can omit manually adding the delimiter length to find the total number of bytes already processed through the stream. (assumes the start position is set to property buffer.start) `buffer.start+buffer.length` vs `buffer.start+buffer.length+os.EOL` but it's really just a nice to have as its possible to work around not having it.

**Comment by maxogden** [comment]
@soldair so basically you want a new bool option like `includeLineEndings`? also by 'start position in source stream' do you mean the absolute byte offset into the stream (for restart purposes)? Cause I would think you could implement that yourself as an e.g. through stream

**Comment by soldair** [comment]
Yes includeLineEndings would be useful because it presents the last line fragment problem in a way the user can handle it.

Yes, absolute byte offset. Piping through another stream is just another layer for something we already have on hand.  My feeling after working around it in exactly this way is that it would be best at home here which is why i  opened the issue.

**Comment by soldair** [comment]
scratched my own itch by sending up a 1.0.0 of a super old line-stream module i had https://github.com/soldair/node-line-stream
